# Generated by Django 4.2.5 on 2023-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Refreshment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='additional_refreshments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_name',
            field=models.CharField(default='Board room1', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='meeting_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, to='api.equipment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refreshments',
            field=models.ManyToManyField(blank=True, to='api.refreshment'),
        ),
    ]
