# Generated by Django 4.2.5 on 2023-09-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reservation_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='equipment_needed',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='refreshments',
        ),
    ]
