# Generated by Django 4.2.5 on 2023-09-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reservation_equipment_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='equipment_needed',
            field=models.ManyToManyField(blank=True, to='api.equipment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='refreshments',
            field=models.ManyToManyField(blank=True, to='api.refreshment'),
        ),
    ]
