# Generated by Django 4.2.5 on 2023-10-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_room_reservation_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_available',
        ),
    ]
