# Generated by Django 4.2.5 on 2023-10-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0009_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_registration_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_registration_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
